### ISSUE TITLE
Local files derail shuffle

### ISSUE THREAD

**Issue by tafk7** [Optidox/SpotifyShuffler#1]
Seems that playlists with local songs (not on spotify, referenced from my devices files) cause the shuffle to stop. Attempted to shuffle a playlist of ~600 songs, but stopped around 15 (which makes sense in terms of how many of them are local).

Cool app btw, definitely will be following its progress.

**Comment by Optidox** [comment]
Issue was resolved in the most recent commit by addition of is_local JSON flag check in app/api_calls.py

Thank you for your report and your compliment.
